### ISSUE TITLE
Possible issue with Externals.cfg?

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/FVdycoreCubed_GridComp#4]
The Externals looks like:
https://github.com/GEOS-ESM/FVdycoreCubed_GridComp/blob/99e8887cadfc2aaac920637e035f4e0cd0b381b3/Externals.cfg#L1-L9

Just for my own edification, should the 1.0.1 be referring to the tag of GFDL_atmos_cubed_sphere? You changed the schema for externals_description instead to 1.0.1.

As a note, the new version of GFDL_atmos_cubed_sphere is v1.0.1 and not geos/v1.0.1.

**Comment by tclune** [comment]
double oops!!!

Fixed manually on GitHub, including deleting  the v1.0.1 tag in the other repo.  (Glad I have not protected the branches yet!)

Sort of surprised any of this worked, but the "close enough" tags did exist for testing.
