### ISSUE TITLE
String formatting error in AdvCore_GridCompMod.F90

### ISSUE THREAD

**Issue by lizziel** [GEOS-ESM/FVdycoreCubed_GridComp#71]
Intel compilers catch a bug in AdvCore_GridCompMod.F90 when debug flags are turned on. The issue is parameter ntracers is set to 11, but then then tracers-1 in a loop over ntracers is printed as integer length 1.

https://github.com/GEOS-ESM/FVdycoreCubed_GridComp/blob/5954a161eade1e850950cd4446986ea0974bd2bd/AdvCore_GridCompMod.F90#L84-L86

https://github.com/GEOS-ESM/FVdycoreCubed_GridComp/blob/5954a161eade1e850950cd4446986ea0974bd2bd/AdvCore_GridCompMod.F90#L220-L222

**Comment by tclune** [comment]
Just to be certain I've understood:   the "bug" is that the final iteration of the loop is printing "10" with a format that is only valid for integers that have 1 digit?

**Comment by tclune** [comment]
I presume the FP divide-by-zero error is indirect and due to the fact that the wrong string is found in `myTracer`?

**Comment by lizziel** [comment]
@sdeastham encountered this bug and fixed it so I will defer to him on this. It is also discussed here (the original report was for GCHPctm): https://github.com/geoschem/GCHPctm/issues/37

**Comment by tclune** [comment]
Mentioning @wmputman 

Bill - do we want to decrease `ntracers` here or do we want to fix the format to be `i2.2`?   It's not clear to me what the origins of the value "11" are.

**Comment by sdeastham** [comment]
Hi Tom - I think the div-by-zero is unrelated. We just noticed that we can't run GCHPctm with debug flags because this minor bug with string formatting will get thrown _first_. Reducing `ntracers` to 10 didn't seem to cause any issues and resolved the specific problem of getting a formatting error, but that was of course in our rather limited GCHP environment.

**Comment by tclune** [comment]
I think @wmputman might be on vacation this week.    We can either put in the `i2.2` fix or wait for his return.

Amusingly @mathomp4 just pinged be about the same problem.   He had not seen this issue.

**Comment by mathomp4** [comment]
I went back in time on CVS and the blame is putting the change to 11 (in DynCore, at least) to:

> revision 1.1.2.2.2.4.2.1.2.3.10.1.4.1.2.1.6.2.2.5.4.14.4.2.2.1
> date: 2014-11-03 16:56:22 -0500;  author: bmauer;  state: Exp;  lines: +838 -282;  commitid: OP17sULzZ6dvRMWx;
> bma: merge of Heracles-1_0_UNSTABLE with wmp-Ganymed-4_0_BETA8-AdvCore-Update4 in the FV3 directory.

So unless @bena-nasa or @wmputman can remember what `wmp-Ganymed-4_0_BETA8-AdvCore-Update4` was ( 😄 ), it might be down to Bill's memory.

**Comment by lizziel** [comment]
I am testing with the simple fix of using 2.2 and found I need to make one additional change to get through advection with debug flags on. When filling the export states for the test tracers I had to pull the N conditional out to before calling MAPL_GetPointer. This avoids an error in Get_Pointer.H if N is greater than ntracers. So this code:
https://github.com/GEOS-ESM/FVdycoreCubed_GridComp/blob/5954a161eade1e850950cd4446986ea0974bd2bd/AdvCore_GridCompMod.F90#L813-L819

became this:

```
 ! Fill Export States
            if ( N <= ntracers ) then
               write(myTracer, "('TEST_TRACER',i2.2)") N-1
               call MAPL_GetPointer(EXPORT, temp3D, TRIM(myTracer), rc=status)
               VERIFY_(STATUS)
               if ( associated(temp3D) ) then
                  temp3D = TRACERS(:,:,:,N)
               endif
             endif
```

**Comment by tclune** [comment]
Hmm.    I now wonder how this ever worked in GEOS.    The `VERIFY_(STATUS)` on line 816 should have failed in many configurations.   The GCM does not generally exercise this, but the CTM does and certainly usually has more tracers than ntracers.

Unfortunately I think we need to investigate a "working" case to see what happens in this loop.

**Comment by mathomp4** [comment]
Well, I can say that if I change all the appropriate `i1.1` to `i2.2` in `DynCore_GridCompMod.F90` the model seems zero-diff. Now, I have *no* idea if I'm actually exercising that code path, but it's a good sign. So perhaps those changes along with those of @lizziel would be okay (if approved by @wmputman)

**Comment by tclune** [comment]
I have word that he returns on Thursday, so we can maybe approve by Friday.

**Comment by mathomp4** [comment]
Also, @tclune brought up that we might want to move from `i1.1` to maybe `i3.3` or even `i5.5` if we make a change. No guarantee people won't run with lots of tracers at some point!

**Comment by tclune** [comment]
My reasoning:  I know that there are projects that use Kppa with O(10^4) species, but that is combustion not advection/CTM.  But  we certainly know CTM's that use hundreds of species.    So `i3.3` is safe for the moment and `i4.4` should be safe for foreseeable configurations.    At that point `i5.5` seems like just a prudent thing with little harm.   We'll already be lost in a sea of 0's in the log by then anyway.

**Comment by tclune** [comment]
Pinging @wmputman again.    We just want to confirm that the proper fix is to edit the formatting to use more characters for the tracer index.  And if you have an opinion, how many characters is "safe" looking into the future.

**Comment by tclune** [comment]
I'm going to go ahead and do a PR with `i5.5` given the lack of response.
