### ISSUE TITLE
Problematic use of MAPL

### ISSUE THREAD

**Issue by tclune** [GEOS-ESM/FVdycoreCubed_GridComp#88]
This line: 
https://github.com/GEOS-ESM/FVdycoreCubed_GridComp/blob/b4a79ce31c60061452ca43ddd51e0477d3921649/CubeGridPrototype.F90#L10
is causing problems because that layer is being refactored.  The correct approach should always be
```
use MAPL, only: ...
```
Doing an ugly workaround in MAPL for now so that this does not get in the way.

**Comment by mathomp4** [comment]
True. I could make a PR for this quickly. As long as it builds, it must work.

**Comment by tclune** [comment]
Sure.  If it gets accepted in time, I can even remove my kludge in MAPL before it's PR
