### ISSUE TITLE
AGCM_IMPORT_RST regridding broken in interp_restart.x

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/FVdycoreCubed_GridComp#99]
At some point some code changes related to use the PFIO metadata layer in MAPL_IO broke the ability of interp_restart.x to regrid agcm_import_rst. In particular the IOChangeRes routine changed where now the user must pass the dimension name and size they wish to change. In interp_restarts.x there is no test done to see if the input file has an edge dimension and take the appropriate action.

**Comment by tclune** [comment]
To be clear, the code changes that broke things were not in PFIO itself, correct?  It was the adaptation of MAPL_IO to use PFIO that broke the utility that uses MAPL_IO.  Or have I misunderstood?
